/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jakc.payment.os.gui;

import java.sql.Connection;
import org.jakc.payment.os.controller.TarifStikerGridController;
import org.openswing.swing.mdi.client.InternalFrame;
import org.openswing.swing.util.java.Consts;

/**
 *
 * @author wahhid
 */
public class TarifStikerGridFrame extends InternalFrame {

    private TarifStikerGridController controller;
    private Connection conn;
    /**
     * Creates new form TarifStikerGridFrame
     */
    public TarifStikerGridFrame(TarifStikerGridController controller,Connection conn) {
        initComponents();
        this.insertButton1.setText("Insert");
        this.editButton1.setText("Edit");
        this.saveButton1.setText("Save");
        this.reloadButton1.setText("Reload");
        this.filterButton1.setText("Find");
        this.deleteButton1.setText("Delete");        
        this.conn = conn;
        this.controller = controller;            
        this.cbjenismobil.setDomain(this.controller.getBc().getJenisMobilController().getCB());
        this.cbjenislangganan.setDomain(this.controller.getBc().getTarifStikerController().getCBJenisStiker());
        this.gridControl2.setController(controller);
        this.gridControl2.setGridDataLocator(controller);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertButton1 = new org.openswing.swing.client.InsertButton();
        editButton1 = new org.openswing.swing.client.EditButton();
        saveButton1 = new org.openswing.swing.client.SaveButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        filterButton1 = new org.openswing.swing.client.FilterButton();
        navigatorBar1 = new org.openswing.swing.client.NavigatorBar();
        gridControl2 = new org.openswing.swing.client.GridControl();
        cbjenislangganan = new org.openswing.swing.table.columns.client.ComboColumn();
        cbjenismobil = new org.openswing.swing.table.columns.client.ComboColumn();
        currencyColumn1 = new org.openswing.swing.table.columns.client.CurrencyColumn();

        setTitle("Tarif Stiker");
        setUniqueInstance(true);

        insertButton1.setButtonBehavior(Consts.BUTTON_IMAGE_AND_TEXT);

        editButton1.setButtonBehavior(Consts.BUTTON_IMAGE_AND_TEXT);

        saveButton1.setButtonBehavior(Consts.BUTTON_IMAGE_AND_TEXT);

        deleteButton1.setButtonBehavior(Consts.BUTTON_IMAGE_AND_TEXT);

        reloadButton1.setButtonBehavior(Consts.BUTTON_IMAGE_AND_TEXT);

        filterButton1.setButtonBehavior(Consts.BUTTON_IMAGE_AND_TEXT);

        gridControl2.setDeleteButton(deleteButton1);
        gridControl2.setEditButton(editButton1);
        gridControl2.setEditOnSingleRow(true);
        gridControl2.setFilterButton(filterButton1);
        gridControl2.setInsertButton(insertButton1);
        gridControl2.setNavBar(navigatorBar1);
        gridControl2.setReloadButton(reloadButton1);
        gridControl2.setSaveButton(saveButton1);
        gridControl2.setValueObjectClassName("org.jakc.payment.os.vo.TarifStikerVo");
        gridControl2.getColumnContainer().setLayout(new java.awt.GridLayout(1, 0));

        cbjenislangganan.setColumnFilterable(true);
        cbjenislangganan.setColumnName("jenis_langganan");
        cbjenislangganan.setColumnSortable(true);
        cbjenislangganan.setEditableOnEdit(true);
        cbjenislangganan.setEditableOnInsert(true);
        gridControl2.getColumnContainer().add(cbjenislangganan);

        cbjenismobil.setColumnFilterable(true);
        cbjenismobil.setColumnName("id_mobil");
        cbjenismobil.setColumnSortable(true);
        cbjenismobil.setEditableOnEdit(true);
        cbjenismobil.setEditableOnInsert(true);
        gridControl2.getColumnContainer().add(cbjenismobil);

        currencyColumn1.setColumnFilterable(true);
        currencyColumn1.setColumnName("tarif");
        currencyColumn1.setColumnSortable(true);
        currencyColumn1.setCurrencySymbol("Rp");
        currencyColumn1.setEditableOnEdit(true);
        currencyColumn1.setEditableOnInsert(true);
        gridControl2.getColumnContainer().add(currencyColumn1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gridControl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reloadButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(navigatorBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navigatorBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reloadButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gridControl2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.ComboColumn cbjenislangganan;
    private org.openswing.swing.table.columns.client.ComboColumn cbjenismobil;
    private org.openswing.swing.table.columns.client.CurrencyColumn currencyColumn1;
    private org.openswing.swing.client.DeleteButton deleteButton1;
    private org.openswing.swing.client.EditButton editButton1;
    private org.openswing.swing.client.FilterButton filterButton1;
    private org.openswing.swing.client.GridControl gridControl2;
    private org.openswing.swing.client.InsertButton insertButton1;
    private org.openswing.swing.client.NavigatorBar navigatorBar1;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.client.SaveButton saveButton1;
    // End of variables declaration//GEN-END:variables
}
